baseURL: https://sonakshigupta.netlify.app
languageCode: en-us
title: Portfolio website for Sonakshi Gupta
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: This is my portfolio filled with models that I have toiled over for hours. Hope you find it interesting! 
      #A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      #AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Sonakshi
  blog: {}
  contact:
    address:
      - city: London, NW1 4SA
        country: United Kingdom
        street: London Business School, Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: sgupta.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: Available upon request
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com/sonakshi180999
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
#      - icon: fa-instagram
#        label: Instagram
#        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/Sonakshi1999
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com
  image: ''
  name: Your name
  navigation:
    button1:
      - name: My CV
        url: blogs
#    button2:
#      - name: Log In
#        url: '#'
    links:
      - name: Home
        url: '#'
      - name: All About Me
        url: blogs/risk_return
      - name: My Projects
        url: blogs
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: When I am not doing statistics
        title: All About Me!
        url: blogs/All_About_Me
      - image: pic02.jpg
        subtitle: This is what got me to LBS!
        title: CV
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
#      - image: pic05.jpg
#        subtitle: Ipsum Dolor Sit Amet
#        title: Consequat
#        url: blogs/ipsum
#      - image: pic06.jpg
#        subtitle: Feugiat Amet Tempus
#        title: Etiam
#        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
